### ISSUE TITLE
Allow for heading range to end at heading with higher depth

### ISSUE THREAD

**Issue by Murderlon** [syntax-tree/mdast-util-heading-range#7]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The document I'm formatting looks like this in terms of headings:

```md
<!-- more above -->

### `getUploadParameters(file)`

### `locale: {}`

## S3 Bucket configuration

## POST uploads

## S3 alternatives
### DigitalOcean Spaces
### Google Cloud Storage
#### JSON CORS configuration

## Examples
### Generating a presigned upload URL server-side
### Retrieving presign parameters of the uploaded file
```

I'm using `headingRange` with ``locale: {}`` passed as `string`.

As the `readme.md` states:

>  A “section” is a heading that passes test, until the next heading of the **same or lower depth** [...]

This means the entire document after `locale: {}` is deleted but for my use case it would be required to also stop at the next heading of a higher depth.

### Solution

Perhaps an `options.endAtNextHeading` (`boolean`, default `false`)

### Alternatives

- Make the new default to also stop at a heading of a higher depth. This would be a breaking change.
- Something more granular, an option to pass an array of heading depths to end at. Overkill?
- Suggest `mdast-zone` if you want this. Although not preferable.

**Comment by wooorm** [comment]
wait, you’re looking for `locale`, and it doesn’t stop at `S3 Bucket configuration`?

**Comment by Murderlon** [comment]
So it happened [here](https://github.com/transloadit/uppy/pull/3276/files/660173825a3e126fb32ddc97a77848a8246a62f9#r738381027) and I figured that must be the case as the `readme` confirms it. But when I try to [reproduce](https://codesandbox.io/s/remark-debug-ikwvx?file=/src/index.js:0-1078) it it seems to work as expected. Might be an issue on my side after all.

**Comment by Murderlon** [comment]
Can confirm that something weird happened at some point, I don't know how, but it seems to work now so this can be ignored.

**Comment by wooorm** [comment]
weird!
